/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Models.Cliente;
import Models.ServicoHistorico;
import Models.Usuario;
import RN.RNCliente;
import RN.RNServico;
import RN.RNUsuario;
import java.util.ArrayList;
import Util.Util;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class FrmAdministrar extends javax.swing.JFrame {

    ArrayList<Usuario> arrUsuarios;
    
    /**
     * Creates new form FrmAdministrar
     */
    public FrmAdministrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblServicosNovos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblClientesNovos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblServicos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Serviços prestados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 99, -1, -1));

        lblServicosNovos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblServicosNovos.setText("0");
        getContentPane().add(lblServicosNovos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 120, 104, 23));

        jLabel3.setText("Clientes novos ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 161, -1, -1));

        lblDashboard.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDashboard.setText("Dashboard 25/11");
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 34, -1, -1));

        lblClientesNovos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblClientesNovos.setText("0");
        getContentPane().add(lblClientesNovos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 184, 104, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Geral");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 230, -1, -1));

        jLabel4.setText("Serviços Registrados");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 274, -1, -1));

        lblServicos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblServicos.setText("0");
        getContentPane().add(lblServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 295, 104, 23));

        jLabel6.setText("Clientes Registrados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 336, -1, -1));

        lblClientes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblClientes.setText("0");
        getContentPane().add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 357, 99, 19));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cargo", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 99, 365, 219));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("Usuários do sistema");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 78, -1, -1));

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("+ Novo usuário");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 78, -1, -1));

        jButton1.setText("Acessar área de trabalho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 345, 365, 31));

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 34, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/adm.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon("src\\resouces\\icone.png").getImage());
        
        carregaDados();
    }//GEN-LAST:event_formWindowOpened

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        
        switch (column) {
        // apagar
            case 3:
                excluirUsuario(row);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        FrmCadastrarUsuario cadastro = new FrmCadastrarUsuario();
        
        cadastro.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       FrmMenu menu = new FrmMenu();
       menu.idUsuario = 0;
       menu.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        carregaDados();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        setVisible(false);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed
    
    private void excluirUsuario(int row){
        
        JPanel panel = new JPanel();
        panel.add(new JLabel("Deseja realmente excluir o usuário?"));

        int result = JOptionPane.showOptionDialog(null, panel, "Excluir Usuário",
                JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, null, null);
        
        if (result == JOptionPane.YES_OPTION){
            new RNUsuario().excluirUsuario(arrUsuarios.get(row).getId());
            carregaDados();
        }
    }
    
    private void carregaDados()
    {
        lblDashboard.setText("Dashboard " + Util.dataToString(Calendar.getInstance().getTime()).substring(0, 5));
        RNCliente rnClientes = new RNCliente();
        ArrayList<Cliente> arrCliente = rnClientes.listarTodosUsuarios("");
        ArrayList<ServicoHistorico> arrServicos = new RNServico().retornaHistoricoServicos(0);
        int iQtdClienteNovo = 0;
        int iQtdServicoHj = 0;
        
        for (Cliente cliente: arrCliente){
            if (Util.dataToString(cliente.getDtCadastro()).equals(Util.dataToString(Calendar.getInstance().getTime()))){
                iQtdClienteNovo += 1;
            }
        }
        
        for (ServicoHistorico servHistoorico: arrServicos){
            if (Util.dataToString(servHistoorico.getDtPrestacaoServico()).equals(Util.dataToString(Calendar.getInstance().getTime()))){
                iQtdServicoHj += 1;
            }
        }
        
        lblServicos.setText(String.valueOf(arrServicos.size()));
        lblServicosNovos.setText(String.valueOf(iQtdServicoHj));
        
        DefaultTableModel tblUsuariosModel = null;
        tblUsuariosModel = (DefaultTableModel) tblUsuarios.getModel();
        tblUsuariosModel.getDataVector().clear();
        tblUsuariosModel.fireTableDataChanged();
        
        arrUsuarios = new RNUsuario().listarTodosUsuarios();
        
        for (Usuario usuario : arrUsuarios)
        {
            tblUsuariosModel.addRow(new Object[]{
                usuario.getId(),
                usuario.getUsuario(),
                usuario.getCargo(), 
                "Apagar"
            });
        }
        
        lblClientesNovos.setText(String.valueOf(iQtdClienteNovo));
        lblClientes.setText(String.valueOf(arrCliente.size()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblClientesNovos;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblServicos;
    private javax.swing.JLabel lblServicosNovos;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}